name: Template Industrialisation workflow pour les pull requests vers le master

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10","3.11"]
    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }} # test de plusieurs versions python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  

      - name: Instalation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Définir les variables d'environnement
        run: |
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}" >> $GITHUB_ENV
          echo "FLASK_PORT=5000" >> $GITHUB_ENV

      - name: Test des fonctions de l'application
        id: test_app
        run: |
          python -m pytest tests/test_app.py

      - name: Test des endpoints de l'application
        id: test_endpoints
        run : |
          python -m pytest tests/test_endpoints.py
  release:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout le code
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installer le package python semantic release
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Vérification des commits # pour forcer les gens à faire des bons commits
        uses: wagoid/commitlint-github-action@v5

      - name: Générer une nouvelle version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release publish
  

