name: Release Workflow

on:
  push:
    branches:
      - master  

permissions:
  contents: write  # pour release et tag
  issues: write    # pourcommenter les issue
  pull-requests: write  # pour gerer les pr 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Installer le package python semantic release
        run: |
            python -m pip install --upgrade pip
            pip install python-semantic-release
      - name: Générer une nouvelle version
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release publish